# -----------------------
# Authentication
# -----------------------

@authUrl = login.microsoftonline.com/{{TENANT_ID}}
@tsiApi = https%3A%2F%2Fapi.timeseries.azure.com%2F

###
# @name tsiLogin
POST https://{{authUrl}}/oauth2/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id={{CLIENT_ID}}&client_secret={{CLIENT_SECRET}}&resource={{tsiApi}}

###
@tsiToken = {{tsiLogin.response.body.access_token}}


# -----------------------
# Environments
# -----------------------

###
# @name environments
GET https://api.timeseries.azure.com/environments?api-version=2016-12-12
Authorization: Bearer {{tsiToken}}
Content-Type: application/json

###
@myEnv = {{environments.response.body.environments[0].environmentId}}



# -----------------------
# Events
# -----------------------

POST https://{{myEnv}}.env.timeseries.azure.com/timeseries/query?api-version=2018-11-01-preview
Authorization: Bearer {{tsiToken}}
Content-Type: application/json

{
  "getEvents": {
    "timeSeriesId": [
      "OL-GEN-1-INST"
    ],
    "searchSpan": {
        "from":  "2019-05-29T00:00:00Z",
        "to":  "2019-05-29T00:01:00Z"
    },
    "projectedProperties": [
      {"name":"events_temperature_value","type":"Double"},
      {"name":"events_temperature_units","type":"Double"},
      {"name":"events_temperature_status","type":"Double"}
    ],
    "filter": { "tsx": "($event.events_temperature_value.Double != null) AND ($event.events_temperature_status.Double = 192.0)" }
  }
}

###
POST https://{{myEnv}}.env.timeseries.azure.com/timeseries/query?api-version=2018-11-01-preview
Authorization: Bearer {{tsiToken}}
Content-Type: application/json

{
  "getEvents": {
    "timeSeriesName" : "PI-00001",
    "searchSpan": {
      "from":  "2019-05-29T00:00:00Z",
      "to":  "2019-05-29T00:01:00Z"
    }
  }
}


###
POST https://{{myEnv}}.env.timeseries.azure.com/timeseries/query?api-version=2018-11-01-preview
Authorization: Bearer {{tsiToken}}
Content-Type: application/json

{
  "getSeries": {
    "timeSeriesId": [
      "OL-GEN-1-INST"
    ],
    "searchSpan": {
      "from":  "2019-05-29T00:00:00Z",
      "to":  "2019-05-29T00:01:00Z"
    },
    "projectedVariables": ["Pressure", "SuctionPressure", "DischargePressure"]
  }
}


###
POST https://{{myEnv}}.env.timeseries.azure.com/timeseries/query?api-version=2018-11-01-preview
Authorization: Bearer {{tsiToken}}
Content-Type: application/json

{
  "getEvents": {
    "timeSeriesId": [
      "OL-GEN-1-INST",
      "OL-GEN-2-INST"
    ],
    "searchSpan": {
      "from":  "2019-05-29T00:00:00Z",
      "to":  "2019-05-29T00:01:00Z"
    }
  }
}
